proxy:
  title: Servidor ShinyProxy Para Apps en R
  template-path: /opt/shinyproxy/templates
  template-resource-path: /opt/shinyproxy/www
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: admin
  
  users:
    - name: marin
      password: 1234
      groups: admin
    - name: jeff
      password: password
      groups: user
    - name: noapp
      password: noapp
      groups: noapp
    
  #proxy.default-websocket-reconnection-mode: auto
  #proxy.my-apps-mode: Modal
  container-wait-time: 60000
  docker:
    internal-networking: false
    #container-network: shinyproxy-net
    endpoint: unix:///var/run/docker.sock
    
  
  specs:
    - id: app_r
      display-name: Mi App En R
      description: App de Shiny R 
      container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/app.R', host='0.0.0.0', port=3838)"]
      container-image: mi-shiny-app
      container-logo: https://www.openanalytics.eu/shinyproxy/logo.png
      docker-image-pull-policy: Never
      access-groups: [ admin, user ]
    - id: app2_r
      display-name: App en R 2
      description: App 2 de Shiny R 
      container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/app2.R', host='0.0.0.0', port=3838)"]
      container-image: mi-shiny-app
      container-logo: https://www.openanalytics.eu/shinyproxy/logo.png
      docker-image-pull-policy: Never
      access-groups: [ admin ]
    - id: app3_r
      display-name: App en R 3
      description: App 3 de Shiny R
      container-volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
      container-cmd: ["/usr/bin/shiny-server"]
      container-image: mi-shiny-app
      container-logo: https://www.openanalytics.eu/shinyproxy/logo.png
      docker-image-pull-policy: Never
      access-groups: [ admin, user ]

management:
  server:
    port: 9001

logging:
  level:
    root: INFO
  file:
    name: shinyproxy.log
